# docker-compose version
version: "3"

# do service containers
services:
  db:
    container_name: spring-db
    image: mysql
    environment:
      MYSQL_DATABASE: spring_db
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring_pw
      MYSQL_ROOT_PASSWORD: root_pw
    volumes:
      - ./db/data:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    restart: always
  app:
    container_name: spring-app
    image: openjdk:11-jdk
    ports:
      - "8082:8082"
    volumes:
      - ./app:/app
    working_dir: /app
    #command: ["./gradlew", "bootrun"]
    depends_on:
      - db
    restart: always
